<?php
/**
 * Backup
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 9.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Backup Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Backup implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Backup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'website_id' => 'string',
        'started_at' => 'string',
        'finished_at' => 'string',
        'snapshot_dir_name' => 'string',
        'size' => 'int',
        'home_dir_status' => '\OpenAPI\Client\Model\OperationStatus',
        'files_size' => 'int',
        'mysql_dbs_status' => '\OpenAPI\Client\Model\OperationStatus',
        'mysql_dbs_count' => 'int',
        'mysql_dbs_size' => 'int',
        'emails_status' => '\OpenAPI\Client\Model\OperationStatus',
        'emails_count' => 'int',
        'emails_size' => 'int',
        'kind' => '\OpenAPI\Client\Model\BackupKind'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'website_id' => 'uuid',
        'started_at' => 'datetime',
        'finished_at' => 'datetime',
        'snapshot_dir_name' => 'filename',
        'size' => null,
        'home_dir_status' => null,
        'files_size' => null,
        'mysql_dbs_status' => null,
        'mysql_dbs_count' => null,
        'mysql_dbs_size' => null,
        'emails_status' => null,
        'emails_count' => null,
        'emails_size' => null,
        'kind' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'website_id' => 'websiteId',
        'started_at' => 'startedAt',
        'finished_at' => 'finishedAt',
        'snapshot_dir_name' => 'snapshotDirName',
        'size' => 'size',
        'home_dir_status' => 'homeDirStatus',
        'files_size' => 'filesSize',
        'mysql_dbs_status' => 'mysqlDbsStatus',
        'mysql_dbs_count' => 'mysqlDbsCount',
        'mysql_dbs_size' => 'mysqlDbsSize',
        'emails_status' => 'emailsStatus',
        'emails_count' => 'emailsCount',
        'emails_size' => 'emailsSize',
        'kind' => 'kind'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'website_id' => 'setWebsiteId',
        'started_at' => 'setStartedAt',
        'finished_at' => 'setFinishedAt',
        'snapshot_dir_name' => 'setSnapshotDirName',
        'size' => 'setSize',
        'home_dir_status' => 'setHomeDirStatus',
        'files_size' => 'setFilesSize',
        'mysql_dbs_status' => 'setMysqlDbsStatus',
        'mysql_dbs_count' => 'setMysqlDbsCount',
        'mysql_dbs_size' => 'setMysqlDbsSize',
        'emails_status' => 'setEmailsStatus',
        'emails_count' => 'setEmailsCount',
        'emails_size' => 'setEmailsSize',
        'kind' => 'setKind'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'website_id' => 'getWebsiteId',
        'started_at' => 'getStartedAt',
        'finished_at' => 'getFinishedAt',
        'snapshot_dir_name' => 'getSnapshotDirName',
        'size' => 'getSize',
        'home_dir_status' => 'getHomeDirStatus',
        'files_size' => 'getFilesSize',
        'mysql_dbs_status' => 'getMysqlDbsStatus',
        'mysql_dbs_count' => 'getMysqlDbsCount',
        'mysql_dbs_size' => 'getMysqlDbsSize',
        'emails_status' => 'getEmailsStatus',
        'emails_count' => 'getEmailsCount',
        'emails_size' => 'getEmailsSize',
        'kind' => 'getKind'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['website_id'] = $data['website_id'] ?? null;
        $this->container['started_at'] = $data['started_at'] ?? null;
        $this->container['finished_at'] = $data['finished_at'] ?? null;
        $this->container['snapshot_dir_name'] = $data['snapshot_dir_name'] ?? null;
        $this->container['size'] = $data['size'] ?? null;
        $this->container['home_dir_status'] = $data['home_dir_status'] ?? null;
        $this->container['files_size'] = $data['files_size'] ?? null;
        $this->container['mysql_dbs_status'] = $data['mysql_dbs_status'] ?? null;
        $this->container['mysql_dbs_count'] = $data['mysql_dbs_count'] ?? null;
        $this->container['mysql_dbs_size'] = $data['mysql_dbs_size'] ?? null;
        $this->container['emails_status'] = $data['emails_status'] ?? null;
        $this->container['emails_count'] = $data['emails_count'] ?? null;
        $this->container['emails_size'] = $data['emails_size'] ?? null;
        $this->container['kind'] = $data['kind'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['website_id'] === null) {
            $invalidProperties[] = "'website_id' can't be null";
        }
        if ($this->container['started_at'] === null) {
            $invalidProperties[] = "'started_at' can't be null";
        }
        if ($this->container['snapshot_dir_name'] === null) {
            $invalidProperties[] = "'snapshot_dir_name' can't be null";
        }
        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets website_id
     *
     * @return string
     */
    public function getWebsiteId()
    {
        return $this->container['website_id'];
    }

    /**
     * Sets website_id
     *
     * @param string $website_id website_id
     *
     * @return self
     */
    public function setWebsiteId($website_id)
    {
        $this->container['website_id'] = $website_id;

        return $this;
    }

    /**
     * Gets started_at
     *
     * @return string
     */
    public function getStartedAt()
    {
        return $this->container['started_at'];
    }

    /**
     * Sets started_at
     *
     * @param string $started_at started_at
     *
     * @return self
     */
    public function setStartedAt($started_at)
    {
        $this->container['started_at'] = $started_at;

        return $this;
    }

    /**
     * Gets finished_at
     *
     * @return string|null
     */
    public function getFinishedAt()
    {
        return $this->container['finished_at'];
    }

    /**
     * Sets finished_at
     *
     * @param string|null $finished_at finished_at
     *
     * @return self
     */
    public function setFinishedAt($finished_at)
    {
        $this->container['finished_at'] = $finished_at;

        return $this;
    }

    /**
     * Gets snapshot_dir_name
     *
     * @return string
     */
    public function getSnapshotDirName()
    {
        return $this->container['snapshot_dir_name'];
    }

    /**
     * Sets snapshot_dir_name
     *
     * @param string $snapshot_dir_name snapshot_dir_name
     *
     * @return self
     */
    public function setSnapshotDirName($snapshot_dir_name)
    {
        $this->container['snapshot_dir_name'] = $snapshot_dir_name;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets home_dir_status
     *
     * @return \OpenAPI\Client\Model\OperationStatus|null
     */
    public function getHomeDirStatus()
    {
        return $this->container['home_dir_status'];
    }

    /**
     * Sets home_dir_status
     *
     * @param \OpenAPI\Client\Model\OperationStatus|null $home_dir_status home_dir_status
     *
     * @return self
     */
    public function setHomeDirStatus($home_dir_status)
    {
        $this->container['home_dir_status'] = $home_dir_status;

        return $this;
    }

    /**
     * Gets files_size
     *
     * @return int|null
     */
    public function getFilesSize()
    {
        return $this->container['files_size'];
    }

    /**
     * Sets files_size
     *
     * @param int|null $files_size files_size
     *
     * @return self
     */
    public function setFilesSize($files_size)
    {
        $this->container['files_size'] = $files_size;

        return $this;
    }

    /**
     * Gets mysql_dbs_status
     *
     * @return \OpenAPI\Client\Model\OperationStatus|null
     */
    public function getMysqlDbsStatus()
    {
        return $this->container['mysql_dbs_status'];
    }

    /**
     * Sets mysql_dbs_status
     *
     * @param \OpenAPI\Client\Model\OperationStatus|null $mysql_dbs_status mysql_dbs_status
     *
     * @return self
     */
    public function setMysqlDbsStatus($mysql_dbs_status)
    {
        $this->container['mysql_dbs_status'] = $mysql_dbs_status;

        return $this;
    }

    /**
     * Gets mysql_dbs_count
     *
     * @return int|null
     */
    public function getMysqlDbsCount()
    {
        return $this->container['mysql_dbs_count'];
    }

    /**
     * Sets mysql_dbs_count
     *
     * @param int|null $mysql_dbs_count mysql_dbs_count
     *
     * @return self
     */
    public function setMysqlDbsCount($mysql_dbs_count)
    {
        $this->container['mysql_dbs_count'] = $mysql_dbs_count;

        return $this;
    }

    /**
     * Gets mysql_dbs_size
     *
     * @return int|null
     */
    public function getMysqlDbsSize()
    {
        return $this->container['mysql_dbs_size'];
    }

    /**
     * Sets mysql_dbs_size
     *
     * @param int|null $mysql_dbs_size mysql_dbs_size
     *
     * @return self
     */
    public function setMysqlDbsSize($mysql_dbs_size)
    {
        $this->container['mysql_dbs_size'] = $mysql_dbs_size;

        return $this;
    }

    /**
     * Gets emails_status
     *
     * @return \OpenAPI\Client\Model\OperationStatus|null
     */
    public function getEmailsStatus()
    {
        return $this->container['emails_status'];
    }

    /**
     * Sets emails_status
     *
     * @param \OpenAPI\Client\Model\OperationStatus|null $emails_status emails_status
     *
     * @return self
     */
    public function setEmailsStatus($emails_status)
    {
        $this->container['emails_status'] = $emails_status;

        return $this;
    }

    /**
     * Gets emails_count
     *
     * @return int|null
     */
    public function getEmailsCount()
    {
        return $this->container['emails_count'];
    }

    /**
     * Sets emails_count
     *
     * @param int|null $emails_count emails_count
     *
     * @return self
     */
    public function setEmailsCount($emails_count)
    {
        $this->container['emails_count'] = $emails_count;

        return $this;
    }

    /**
     * Gets emails_size
     *
     * @return int|null
     */
    public function getEmailsSize()
    {
        return $this->container['emails_size'];
    }

    /**
     * Sets emails_size
     *
     * @param int|null $emails_size emails_size
     *
     * @return self
     */
    public function setEmailsSize($emails_size)
    {
        $this->container['emails_size'] = $emails_size;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return \OpenAPI\Client\Model\BackupKind
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param \OpenAPI\Client\Model\BackupKind $kind kind
     *
     * @return self
     */
    public function setKind($kind)
    {
        $this->container['kind'] = $kind;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


