<?php
/**
 * DaemonKind
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 9.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DaemonKind Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DaemonKind
{
    /**
     * Possible values of this enum
     */
    const MYSQLD = 'mysqld';

    const PDNS = 'pdns';

    const POSTFIX_SMTP = 'postfixSmtp';

    const POSTFIX_SMTPS = 'postfixSmtps';

    const POSTFIX_SUBMISSIONS = 'postfixSubmissions';

    const DOVCOT_IMAP = 'dovcotImap';

    const DOVCOT_IMAPS = 'dovcotImaps';

    const DOVCOT_POP3 = 'dovcotPop3';

    const DOVCOT_POP3S = 'dovcotPop3s';

    const PURE_FTP = 'pureFtp';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MYSQLD,
            self::PDNS,
            self::POSTFIX_SMTP,
            self::POSTFIX_SMTPS,
            self::POSTFIX_SUBMISSIONS,
            self::DOVCOT_IMAP,
            self::DOVCOT_IMAPS,
            self::DOVCOT_POP3,
            self::DOVCOT_POP3S,
            self::PURE_FTP
        ];
    }
}


