<?php
/**
 * SubscriptionDedicatedServersInfo
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 9.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SubscriptionDedicatedServersInfo Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SubscriptionDedicatedServersInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SubscriptionDedicatedServersInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'app_server' => '\OpenAPI\Client\Model\SubscriptionDedicatedServer',
        'backup_server' => '\OpenAPI\Client\Model\SubscriptionDedicatedServer',
        'db_server' => '\OpenAPI\Client\Model\SubscriptionDedicatedServer',
        'email_server' => '\OpenAPI\Client\Model\SubscriptionDedicatedServer'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'app_server' => null,
        'backup_server' => null,
        'db_server' => null,
        'email_server' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'app_server' => 'appServer',
        'backup_server' => 'backupServer',
        'db_server' => 'dbServer',
        'email_server' => 'emailServer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'app_server' => 'setAppServer',
        'backup_server' => 'setBackupServer',
        'db_server' => 'setDbServer',
        'email_server' => 'setEmailServer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'app_server' => 'getAppServer',
        'backup_server' => 'getBackupServer',
        'db_server' => 'getDbServer',
        'email_server' => 'getEmailServer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['app_server'] = $data['app_server'] ?? null;
        $this->container['backup_server'] = $data['backup_server'] ?? null;
        $this->container['db_server'] = $data['db_server'] ?? null;
        $this->container['email_server'] = $data['email_server'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets app_server
     *
     * @return \OpenAPI\Client\Model\SubscriptionDedicatedServer|null
     */
    public function getAppServer()
    {
        return $this->container['app_server'];
    }

    /**
     * Sets app_server
     *
     * @param \OpenAPI\Client\Model\SubscriptionDedicatedServer|null $app_server app_server
     *
     * @return self
     */
    public function setAppServer($app_server)
    {
        $this->container['app_server'] = $app_server;

        return $this;
    }

    /**
     * Gets backup_server
     *
     * @return \OpenAPI\Client\Model\SubscriptionDedicatedServer|null
     */
    public function getBackupServer()
    {
        return $this->container['backup_server'];
    }

    /**
     * Sets backup_server
     *
     * @param \OpenAPI\Client\Model\SubscriptionDedicatedServer|null $backup_server backup_server
     *
     * @return self
     */
    public function setBackupServer($backup_server)
    {
        $this->container['backup_server'] = $backup_server;

        return $this;
    }

    /**
     * Gets db_server
     *
     * @return \OpenAPI\Client\Model\SubscriptionDedicatedServer|null
     */
    public function getDbServer()
    {
        return $this->container['db_server'];
    }

    /**
     * Sets db_server
     *
     * @param \OpenAPI\Client\Model\SubscriptionDedicatedServer|null $db_server db_server
     *
     * @return self
     */
    public function setDbServer($db_server)
    {
        $this->container['db_server'] = $db_server;

        return $this;
    }

    /**
     * Gets email_server
     *
     * @return \OpenAPI\Client\Model\SubscriptionDedicatedServer|null
     */
    public function getEmailServer()
    {
        return $this->container['email_server'];
    }

    /**
     * Sets email_server
     *
     * @param \OpenAPI\Client\Model\SubscriptionDedicatedServer|null $email_server email_server
     *
     * @return self
     */
    public function setEmailServer($email_server)
    {
        $this->container['email_server'] = $email_server;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


