<?php
/**
 * WpUserRole
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 9.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WpUserRole Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WpUserRole
{
    /**
     * Possible values of this enum
     */
    const ADMINISTRATOR = 'administrator';

    const AUTHOR = 'author';

    const CONTRIBUTOR = 'contributor';

    const EDITOR = 'editor';

    const SUBSCRIBER = 'subscriber';

    const CUSTOMER = 'customer';

    const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ADMINISTRATOR,
            self::AUTHOR,
            self::CONTRIBUTOR,
            self::EDITOR,
            self::SUBSCRIBER,
            self::CUSTOMER,
            self::OTHER
        ];
    }
}


